// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TaskSharpHTTP.Models;

namespace FcProyecto.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("TaskSharpHTTP.Models.CuentaItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Categoria")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("Char")
                        .HasColumnName("CHARTTYPE");

                    b.Property<string>("Codigo")
                        .HasColumnName("ACCNO");

                    b.Property<string>("Descripcion")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Gifi")
                        .HasColumnName("GIFI_ACCNO");

                    b.Property<string>("Link")
                        .HasColumnName("LINK");

                    b.HasKey("ID");

                    b.ToTable("CHART");
                });
#pragma warning restore 612, 618
        }
    }
}
